# Generated by Django 5.2.14 on 2026-06-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drinks",
            old_name="drink",
            new_name="drink_name",
        ),
    ]
