# Generated by Django 5.2.15 on 2026-07-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("inventory", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["price"], name="BookListAPI_price_779a55_idx")
                ],
            },
        ),
    ]
